# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_mask_editor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mask_editor(object):
    def setupUi(self, mask_editor):
        mask_editor.setObjectName("mask_editor")
        mask_editor.resize(1404, 688)
        mask_editor.setStyleSheet("#mask_editor{background-color: rgb(179, 179, 179);}\n"
"QGroupBox::title{color:rgb(0, 0, 0)}\n"
"QLabel{color:rgb(0, 0, 0)}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(mask_editor)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(mask_editor)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter.setLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(6)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.mask_layout_control = QtWidgets.QVBoxLayout(self.widget)
        self.mask_layout_control.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.mask_layout_control.setContentsMargins(0, 0, 0, 0)
        self.mask_layout_control.setSpacing(0)
        self.mask_layout_control.setObjectName("mask_layout_control")
        self.mask_group_masks = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_group_masks.sizePolicy().hasHeightForWidth())
        self.mask_group_masks.setSizePolicy(sizePolicy)
        self.mask_group_masks.setMinimumSize(QtCore.QSize(0, 0))
        self.mask_group_masks.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mask_group_masks.setObjectName("mask_group_masks")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mask_group_masks)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.combo_layout = QtWidgets.QHBoxLayout()
        self.combo_layout.setContentsMargins(1, 1, 1, 1)
        self.combo_layout.setSpacing(6)
        self.combo_layout.setObjectName("combo_layout")
        self.label = QtWidgets.QLabel(self.mask_group_masks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.combo_layout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.combo_layout)
        self.mask_tree_layout = QtWidgets.QVBoxLayout()
        self.mask_tree_layout.setObjectName("mask_tree_layout")
        self.verticalLayout_2.addLayout(self.mask_tree_layout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mask_button_add = QtWidgets.QPushButton(self.mask_group_masks)
        self.mask_button_add.setObjectName("mask_button_add")
        self.horizontalLayout_2.addWidget(self.mask_button_add)
        self.mask_button_remove = QtWidgets.QPushButton(self.mask_group_masks)
        self.mask_button_remove.setObjectName("mask_button_remove")
        self.horizontalLayout_2.addWidget(self.mask_button_remove)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.mask_label_dimension = QtWidgets.QLabel(self.mask_group_masks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_label_dimension.sizePolicy().hasHeightForWidth())
        self.mask_label_dimension.setSizePolicy(sizePolicy)
        self.mask_label_dimension.setObjectName("mask_label_dimension")
        self.horizontalLayout_2.addWidget(self.mask_label_dimension)
        self.mask_input_x = QtWidgets.QLineEdit(self.mask_group_masks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_input_x.sizePolicy().hasHeightForWidth())
        self.mask_input_x.setSizePolicy(sizePolicy)
        self.mask_input_x.setMinimumSize(QtCore.QSize(50, 0))
        self.mask_input_x.setMaximumSize(QtCore.QSize(50, 16777215))
        self.mask_input_x.setBaseSize(QtCore.QSize(50, 0))
        self.mask_input_x.setAlignment(QtCore.Qt.AlignCenter)
        self.mask_input_x.setObjectName("mask_input_x")
        self.horizontalLayout_2.addWidget(self.mask_input_x)
        self.mask_input_y = QtWidgets.QLineEdit(self.mask_group_masks)
        self.mask_input_y.setMinimumSize(QtCore.QSize(50, 0))
        self.mask_input_y.setMaximumSize(QtCore.QSize(50, 16777215))
        self.mask_input_y.setBaseSize(QtCore.QSize(50, 0))
        self.mask_input_y.setAlignment(QtCore.Qt.AlignCenter)
        self.mask_input_y.setObjectName("mask_input_y")
        self.horizontalLayout_2.addWidget(self.mask_input_y)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.mask_layout_control.addWidget(self.mask_group_masks)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.mask_layout_vis = QtWidgets.QVBoxLayout(self.widget1)
        self.mask_layout_vis.setContentsMargins(10, 0, 0, 0)
        self.mask_layout_vis.setObjectName("mask_layout_vis")
        self.mask_group_visual = QtWidgets.QGroupBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_group_visual.sizePolicy().hasHeightForWidth())
        self.mask_group_visual.setSizePolicy(sizePolicy)
        self.mask_group_visual.setMinimumSize(QtCore.QSize(0, 0))
        self.mask_group_visual.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mask_group_visual.setObjectName("mask_group_visual")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mask_group_visual)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mask_widget_visual = QtWidgets.QWidget(self.mask_group_visual)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_widget_visual.sizePolicy().hasHeightForWidth())
        self.mask_widget_visual.setSizePolicy(sizePolicy)
        self.mask_widget_visual.setMinimumSize(QtCore.QSize(0, 0))
        self.mask_widget_visual.setObjectName("mask_widget_visual")
        self.verticalLayout.addWidget(self.mask_widget_visual)
        self.mask_layout_vis.addWidget(self.mask_group_visual)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(mask_editor)
        QtCore.QMetaObject.connectSlotsByName(mask_editor)

    def retranslateUi(self, mask_editor):
        _translate = QtCore.QCoreApplication.translate
        mask_editor.setWindowTitle(_translate("mask_editor", "Form"))
        self.mask_group_masks.setTitle(_translate("mask_editor", "Mask elements"))
        self.label.setText(_translate("mask_editor", "Set:"))
        self.mask_button_add.setToolTip(_translate("mask_editor", "Add an element to the dataset"))
        self.mask_button_add.setText(_translate("mask_editor", "+"))
        self.mask_button_remove.setToolTip(_translate("mask_editor", "Remove the currently selected element"))
        self.mask_button_remove.setText(_translate("mask_editor", "-"))
        self.mask_label_dimension.setText(_translate("mask_editor", "Dim"))
        self.mask_input_x.setToolTip(_translate("mask_editor", "pixels along x"))
        self.mask_input_x.setText(_translate("mask_editor", "128"))
        self.mask_input_y.setToolTip(_translate("mask_editor", "pixels along y"))
        self.mask_input_y.setText(_translate("mask_editor", "128"))
        self.mask_group_visual.setTitle(_translate("mask_editor", "Visual"))

