# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_script.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_script_widget(object):
    def setupUi(self, script_widget):
        script_widget.setObjectName("script_widget")
        script_widget.resize(1067, 685)
        script_widget.setStyleSheet("#script_widget{background-color: rgb(179, 179, 179);}")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(script_widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(script_widget)
        self.tabWidget.setObjectName("tabWidget")
        self.process_tab = QtWidgets.QWidget()
        self.process_tab.setObjectName("process_tab")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.process_tab)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox_2 = QtWidgets.QGroupBox(self.process_tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.verticalLayout_16.addWidget(self.label)
        self.process_layout_foil_check = QtWidgets.QHBoxLayout()
        self.process_layout_foil_check.setObjectName("process_layout_foil_check")
        self.verticalLayout_16.addLayout(self.process_layout_foil_check)
        self.horizontalLayout_4.addLayout(self.verticalLayout_16)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setContentsMargins(0, 10, -1, -1)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_17.addWidget(self.label_7)
        self.process_list_echo_times = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_list_echo_times.sizePolicy().hasHeightForWidth())
        self.process_list_echo_times.setSizePolicy(sizePolicy)
        self.process_list_echo_times.setMinimumSize(QtCore.QSize(500, 0))
        self.process_list_echo_times.setMaximumSize(QtCore.QSize(500, 16777215))
        self.process_list_echo_times.setBaseSize(QtCore.QSize(500, 0))
        self.process_list_echo_times.setObjectName("process_list_echo_times")
        self.verticalLayout_17.addWidget(self.process_list_echo_times)
        self.horizontalLayout_15.addLayout(self.verticalLayout_17)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setContentsMargins(0, 10, -1, -1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_19.addWidget(self.label_9)
        self.process_list_selected = QtWidgets.QListView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_list_selected.sizePolicy().hasHeightForWidth())
        self.process_list_selected.setSizePolicy(sizePolicy)
        self.process_list_selected.setObjectName("process_list_selected")
        self.verticalLayout_19.addWidget(self.process_list_selected)
        self.horizontalLayout_15.addLayout(self.verticalLayout_19)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(0, 10, -1, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.process_radio_mask = QtWidgets.QRadioButton(self.groupBox_2)
        self.process_radio_mask.setObjectName("process_radio_mask")
        self.verticalLayout_13.addWidget(self.process_radio_mask)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_13.addWidget(self.label_6)
        self.process_box_masks = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_box_masks.sizePolicy().hasHeightForWidth())
        self.process_box_masks.setSizePolicy(sizePolicy)
        self.process_box_masks.setObjectName("process_box_masks")
        self.verticalLayout_13.addWidget(self.process_box_masks)
        self.verticalLayout_18.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(0, 10, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.process_radio_exposure = QtWidgets.QRadioButton(self.groupBox_2)
        self.process_radio_exposure.setObjectName("process_radio_exposure")
        self.verticalLayout_12.addWidget(self.process_radio_exposure)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5)
        self.process_box_refs = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_box_refs.sizePolicy().hasHeightForWidth())
        self.process_box_refs.setSizePolicy(sizePolicy)
        self.process_box_refs.setObjectName("process_box_refs")
        self.verticalLayout_12.addWidget(self.process_box_refs)
        self.verticalLayout_18.addLayout(self.verticalLayout_12)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_18.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_18.addWidget(self.label_2)
        self.process_box_refs_fit = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_box_refs_fit.sizePolicy().hasHeightForWidth())
        self.process_box_refs_fit.setSizePolicy(sizePolicy)
        self.process_box_refs_fit.setObjectName("process_box_refs_fit")
        self.verticalLayout_18.addWidget(self.process_box_refs_fit)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_18.addWidget(self.label_3)
        self.process_box_back_fit = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_box_back_fit.sizePolicy().hasHeightForWidth())
        self.process_box_back_fit.setSizePolicy(sizePolicy)
        self.process_box_back_fit.setObjectName("process_box_back_fit")
        self.verticalLayout_18.addWidget(self.process_box_back_fit)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_18.addWidget(self.label_4)
        self.process_box_mask_fit = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_box_mask_fit.sizePolicy().hasHeightForWidth())
        self.process_box_mask_fit.setSizePolicy(sizePolicy)
        self.process_box_mask_fit.setObjectName("process_box_mask_fit")
        self.verticalLayout_18.addWidget(self.process_box_mask_fit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem1)
        self.horizontalLayout_15.addLayout(self.verticalLayout_18)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.process_button_run_data = QtWidgets.QPushButton(self.groupBox_2)
        self.process_button_run_data.setMinimumSize(QtCore.QSize(150, 0))
        self.process_button_run_data.setMaximumSize(QtCore.QSize(150, 16777215))
        self.process_button_run_data.setObjectName("process_button_run_data")
        self.horizontalLayout_11.addWidget(self.process_button_run_data)
        self.process_button_run_phase = QtWidgets.QPushButton(self.groupBox_2)
        self.process_button_run_phase.setMinimumSize(QtCore.QSize(150, 0))
        self.process_button_run_phase.setMaximumSize(QtCore.QSize(150, 16777215))
        self.process_button_run_phase.setObjectName("process_button_run_phase")
        self.horizontalLayout_11.addWidget(self.process_button_run_phase)
        self.process_button_run_fit = QtWidgets.QPushButton(self.groupBox_2)
        self.process_button_run_fit.setMinimumSize(QtCore.QSize(150, 0))
        self.process_button_run_fit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.process_button_run_fit.setObjectName("process_button_run_fit")
        self.horizontalLayout_11.addWidget(self.process_button_run_fit)
        self.process_button_run_post = QtWidgets.QPushButton(self.groupBox_2)
        self.process_button_run_post.setMinimumSize(QtCore.QSize(150, 0))
        self.process_button_run_post.setMaximumSize(QtCore.QSize(150, 16777215))
        self.process_button_run_post.setObjectName("process_button_run_post")
        self.horizontalLayout_11.addWidget(self.process_button_run_post)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.process_button_script_data = QtWidgets.QPushButton(self.groupBox_2)
        self.process_button_script_data.setMinimumSize(QtCore.QSize(150, 0))
        self.process_button_script_data.setMaximumSize(QtCore.QSize(150, 16777215))
        self.process_button_script_data.setObjectName("process_button_script_data")
        self.horizontalLayout_16.addWidget(self.process_button_script_data)
        self.process_button_script_phase = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_button_script_phase.sizePolicy().hasHeightForWidth())
        self.process_button_script_phase.setSizePolicy(sizePolicy)
        self.process_button_script_phase.setMinimumSize(QtCore.QSize(150, 0))
        self.process_button_script_phase.setMaximumSize(QtCore.QSize(150, 16777215))
        self.process_button_script_phase.setObjectName("process_button_script_phase")
        self.horizontalLayout_16.addWidget(self.process_button_script_phase)
        self.process_button_script_fit = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_button_script_fit.sizePolicy().hasHeightForWidth())
        self.process_button_script_fit.setSizePolicy(sizePolicy)
        self.process_button_script_fit.setMinimumSize(QtCore.QSize(150, 0))
        self.process_button_script_fit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.process_button_script_fit.setObjectName("process_button_script_fit")
        self.horizontalLayout_16.addWidget(self.process_button_script_fit)
        self.process_button_script_post = QtWidgets.QPushButton(self.groupBox_2)
        self.process_button_script_post.setMinimumSize(QtCore.QSize(150, 0))
        self.process_button_script_post.setMaximumSize(QtCore.QSize(150, 16777215))
        self.process_button_script_post.setObjectName("process_button_script_post")
        self.horizontalLayout_16.addWidget(self.process_button_script_post)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_12.addWidget(self.groupBox_2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.script_label_running = QtWidgets.QLabel(self.process_tab)
        self.script_label_running.setObjectName("script_label_running")
        self.horizontalLayout.addWidget(self.script_label_running)
        self.script_bar_running = QtWidgets.QProgressBar(self.process_tab)
        self.script_bar_running.setMinimumSize(QtCore.QSize(150, 0))
        self.script_bar_running.setMaximumSize(QtCore.QSize(150, 16777215))
        self.script_bar_running.setProperty("value", 24)
        self.script_bar_running.setObjectName("script_bar_running")
        self.horizontalLayout.addWidget(self.script_bar_running)
        self.scrip_label_action = QtWidgets.QLabel(self.process_tab)
        self.scrip_label_action.setObjectName("scrip_label_action")
        self.horizontalLayout.addWidget(self.scrip_label_action)
        self.script_label_action_2 = QtWidgets.QLabel(self.process_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.script_label_action_2.sizePolicy().hasHeightForWidth())
        self.script_label_action_2.setSizePolicy(sizePolicy)
        self.script_label_action_2.setMinimumSize(QtCore.QSize(0, 0))
        self.script_label_action_2.setMaximumSize(QtCore.QSize(600, 16777215))
        self.script_label_action_2.setObjectName("script_label_action_2")
        self.horizontalLayout.addWidget(self.script_label_action_2)
        spacerItem6 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_15.addLayout(self.horizontalLayout)
        self.horizontalLayout_13.addLayout(self.verticalLayout_15)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.tabWidget.addTab(self.process_tab, "")
        self.panel_tab = QtWidgets.QWidget()
        self.panel_tab.setObjectName("panel_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.panel_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panel_layout = QtWidgets.QVBoxLayout()
        self.panel_layout.setSpacing(0)
        self.panel_layout.setObjectName("panel_layout")
        self.verticalLayout.addLayout(self.panel_layout)
        self.tabWidget.addTab(self.panel_tab, "")
        self.script_tab = QtWidgets.QWidget()
        self.script_tab.setObjectName("script_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.script_tab)
        self.verticalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.script_tabs = QtWidgets.QTabWidget(self.script_tab)
        self.script_tabs.setStyleSheet("")
        self.script_tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.script_tabs.setObjectName("script_tabs")
        self.script_tab_import = QtWidgets.QWidget()
        self.script_tab_import.setObjectName("script_tab_import")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.script_tab_import)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.script_text_import = QtWidgets.QTextEdit(self.script_tab_import)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.script_text_import.sizePolicy().hasHeightForWidth())
        self.script_text_import.setSizePolicy(sizePolicy)
        self.script_text_import.setObjectName("script_text_import")
        self.verticalLayout_2.addWidget(self.script_text_import)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.script_button_import_gui = QtWidgets.QPushButton(self.script_tab_import)
        self.script_button_import_gui.setObjectName("script_button_import_gui")
        self.horizontalLayout_2.addWidget(self.script_button_import_gui)
        self.script_button_import_run = QtWidgets.QPushButton(self.script_tab_import)
        self.script_button_import_run.setDefault(True)
        self.script_button_import_run.setObjectName("script_button_import_run")
        self.horizontalLayout_2.addWidget(self.script_button_import_run)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.script_tabs.addTab(self.script_tab_import, "")
        self.script_tab_phase = QtWidgets.QWidget()
        self.script_tab_phase.setObjectName("script_tab_phase")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.script_tab_phase)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.script_text_phase = QtWidgets.QTextEdit(self.script_tab_phase)
        self.script_text_phase.setObjectName("script_text_phase")
        self.verticalLayout_3.addWidget(self.script_text_phase)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.script_button_phase_gui = QtWidgets.QPushButton(self.script_tab_phase)
        self.script_button_phase_gui.setObjectName("script_button_phase_gui")
        self.horizontalLayout_5.addWidget(self.script_button_phase_gui)
        self.script_button_phase_run = QtWidgets.QPushButton(self.script_tab_phase)
        self.script_button_phase_run.setDefault(True)
        self.script_button_phase_run.setObjectName("script_button_phase_run")
        self.horizontalLayout_5.addWidget(self.script_button_phase_run)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.script_tabs.addTab(self.script_tab_phase, "")
        self.script_tab_reduction = QtWidgets.QWidget()
        self.script_tab_reduction.setObjectName("script_tab_reduction")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.script_tab_reduction)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.script_text_reduction = QtWidgets.QTextEdit(self.script_tab_reduction)
        self.script_text_reduction.setObjectName("script_text_reduction")
        self.verticalLayout_4.addWidget(self.script_text_reduction)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.script_button_reduction_gui = QtWidgets.QPushButton(self.script_tab_reduction)
        self.script_button_reduction_gui.setObjectName("script_button_reduction_gui")
        self.horizontalLayout_6.addWidget(self.script_button_reduction_gui)
        self.script_button_reduction_run = QtWidgets.QPushButton(self.script_tab_reduction)
        self.script_button_reduction_run.setDefault(True)
        self.script_button_reduction_run.setObjectName("script_button_reduction_run")
        self.horizontalLayout_6.addWidget(self.script_button_reduction_run)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.script_tabs.addTab(self.script_tab_reduction, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.script_text_post = QtWidgets.QTextEdit(self.tab)
        self.script_text_post.setObjectName("script_text_post")
        self.verticalLayout_8.addWidget(self.script_text_post)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.script_button_post_run = QtWidgets.QPushButton(self.tab)
        self.script_button_post_run.setDefault(True)
        self.script_button_post_run.setObjectName("script_button_post_run")
        self.horizontalLayout_7.addWidget(self.script_button_post_run)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.script_tabs.addTab(self.tab, "")
        self.verticalLayout_6.addWidget(self.script_tabs)
        self.tabWidget.addTab(self.script_tab, "")
        self.result_tab = QtWidgets.QWidget()
        self.result_tab.setObjectName("result_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.result_tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.result_tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_14.setSpacing(5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.process_tree_x = QtWidgets.QTreeWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_tree_x.sizePolicy().hasHeightForWidth())
        self.process_tree_x.setSizePolicy(sizePolicy)
        self.process_tree_x.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.process_tree_x.setProperty("showDropIndicator", False)
        self.process_tree_x.setAlternatingRowColors(True)
        self.process_tree_x.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.process_tree_x.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.process_tree_x.setAnimated(False)
        self.process_tree_x.setObjectName("process_tree_x")
        self.process_tree_x.headerItem().setText(0, "1")
        self.process_tree_x.header().setVisible(False)
        self.process_tree_x.header().setCascadingSectionResizes(False)
        self.process_tree_x.header().setHighlightSections(False)
        self.process_tree_x.header().setStretchLastSection(True)
        self.verticalLayout_10.addWidget(self.process_tree_x)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.process_tree_y = QtWidgets.QTreeWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_tree_y.sizePolicy().hasHeightForWidth())
        self.process_tree_y.setSizePolicy(sizePolicy)
        self.process_tree_y.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.process_tree_y.setProperty("showDropIndicator", False)
        self.process_tree_y.setAlternatingRowColors(True)
        self.process_tree_y.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.process_tree_y.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.process_tree_y.setAnimated(False)
        self.process_tree_y.setObjectName("process_tree_y")
        self.process_tree_y.headerItem().setText(0, "1")
        self.process_tree_y.header().setVisible(False)
        self.process_tree_y.header().setCascadingSectionResizes(False)
        self.process_tree_y.header().setHighlightSections(False)
        self.process_tree_y.header().setStretchLastSection(True)
        self.verticalLayout_10.addWidget(self.process_tree_y)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.process_tree_error = QtWidgets.QTreeWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_tree_error.sizePolicy().hasHeightForWidth())
        self.process_tree_error.setSizePolicy(sizePolicy)
        self.process_tree_error.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.process_tree_error.setProperty("showDropIndicator", False)
        self.process_tree_error.setAlternatingRowColors(True)
        self.process_tree_error.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.process_tree_error.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.process_tree_error.setAnimated(False)
        self.process_tree_error.setObjectName("process_tree_error")
        self.process_tree_error.headerItem().setText(0, "1")
        self.process_tree_error.header().setVisible(False)
        self.process_tree_error.header().setCascadingSectionResizes(False)
        self.process_tree_error.header().setHighlightSections(False)
        self.process_tree_error.header().setStretchLastSection(True)
        self.verticalLayout_10.addWidget(self.process_tree_error)
        self.verticalLayout_14.addLayout(self.verticalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.process_button_echo_fit = QtWidgets.QPushButton(self.groupBox)
        self.process_button_echo_fit.setObjectName("process_button_echo_fit")
        self.horizontalLayout_8.addWidget(self.process_button_echo_fit)
        self.process_button_gamma = QtWidgets.QPushButton(self.groupBox)
        self.process_button_gamma.setObjectName("process_button_gamma")
        self.horizontalLayout_8.addWidget(self.process_button_gamma)
        self.verticalLayout_14.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.result_tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.process_widget_plot = QtWidgets.QWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_widget_plot.sizePolicy().hasHeightForWidth())
        self.process_widget_plot.setSizePolicy(sizePolicy)
        self.process_widget_plot.setObjectName("process_widget_plot")
        self.verticalLayout_20.addWidget(self.process_widget_plot)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.process_tree_plot = QtWidgets.QTreeWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_tree_plot.sizePolicy().hasHeightForWidth())
        self.process_tree_plot.setSizePolicy(sizePolicy)
        self.process_tree_plot.setMinimumSize(QtCore.QSize(0, 350))
        self.process_tree_plot.setMaximumSize(QtCore.QSize(16777215, 350))
        self.process_tree_plot.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.process_tree_plot.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.process_tree_plot.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.process_tree_plot.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.process_tree_plot.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.process_tree_plot.setProperty("showDropIndicator", False)
        self.process_tree_plot.setDragEnabled(False)
        self.process_tree_plot.setAlternatingRowColors(True)
        self.process_tree_plot.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.process_tree_plot.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.process_tree_plot.setUniformRowHeights(False)
        self.process_tree_plot.setAnimated(False)
        self.process_tree_plot.setColumnCount(1)
        self.process_tree_plot.setObjectName("process_tree_plot")
        self.process_tree_plot.headerItem().setText(0, "1")
        self.process_tree_plot.header().setVisible(False)
        self.process_tree_plot.header().setCascadingSectionResizes(False)
        self.process_tree_plot.header().setHighlightSections(False)
        self.process_tree_plot.header().setStretchLastSection(False)
        self.verticalLayout_21.addWidget(self.process_tree_plot)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.process_button_plot_add = QtWidgets.QPushButton(self.groupBox_3)
        self.process_button_plot_add.setObjectName("process_button_plot_add")
        self.horizontalLayout_9.addWidget(self.process_button_plot_add)
        self.process_button_plot_remove = QtWidgets.QPushButton(self.groupBox_3)
        self.process_button_plot_remove.setObjectName("process_button_plot_remove")
        self.horizontalLayout_9.addWidget(self.process_button_plot_remove)
        self.process_button_plot_reset = QtWidgets.QPushButton(self.groupBox_3)
        self.process_button_plot_reset.setObjectName("process_button_plot_reset")
        self.horizontalLayout_9.addWidget(self.process_button_plot_reset)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.process_check_offset = QtWidgets.QCheckBox(self.groupBox_3)
        self.process_check_offset.setObjectName("process_check_offset")
        self.horizontalLayout_9.addWidget(self.process_check_offset)
        self.process_spin_offset = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.process_spin_offset.setMinimum(-100000000.0)
        self.process_spin_offset.setMaximum(100000000.0)
        self.process_spin_offset.setObjectName("process_spin_offset")
        self.horizontalLayout_9.addWidget(self.process_spin_offset)
        self.process_spin_offset_total = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.process_spin_offset_total.setMinimum(-100000000.0)
        self.process_spin_offset_total.setMaximum(100000000.0)
        self.process_spin_offset_total.setObjectName("process_spin_offset_total")
        self.horizontalLayout_9.addWidget(self.process_spin_offset_total)
        self.process_check_log_x = QtWidgets.QCheckBox(self.groupBox_3)
        self.process_check_log_x.setObjectName("process_check_log_x")
        self.horizontalLayout_9.addWidget(self.process_check_log_x)
        self.process_check_log_y = QtWidgets.QCheckBox(self.groupBox_3)
        self.process_check_log_y.setObjectName("process_check_log_y")
        self.horizontalLayout_9.addWidget(self.process_check_log_y)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.process_button_plot_hide = QtWidgets.QPushButton(self.groupBox_3)
        self.process_button_plot_hide.setObjectName("process_button_plot_hide")
        self.horizontalLayout_9.addWidget(self.process_button_plot_hide)
        self.process_button_plot_plot = QtWidgets.QPushButton(self.groupBox_3)
        self.process_button_plot_plot.setDefault(True)
        self.process_button_plot_plot.setObjectName("process_button_plot_plot")
        self.horizontalLayout_9.addWidget(self.process_button_plot_plot)
        self.verticalLayout_21.addLayout(self.horizontalLayout_9)
        self.verticalLayout_20.addLayout(self.verticalLayout_21)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.result_tab, "")
        self.verticalLayout_5.addWidget(self.tabWidget)

        self.retranslateUi(script_widget)
        self.tabWidget.setCurrentIndex(3)
        self.script_tabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(script_widget)

    def retranslateUi(self, script_widget):
        _translate = QtCore.QCoreApplication.translate
        script_widget.setWindowTitle(_translate("script_widget", "Form"))
        self.groupBox_2.setTitle(_translate("script_widget", "Fit parameters"))
        self.label.setText(_translate("script_widget", "Foils to be considerd: "))
        self.label_7.setText(_translate("script_widget", "Select the foils to consider for each echo time:"))
        self.label_9.setText(_translate("script_widget", "Select the measurements to consider:"))
        self.process_radio_mask.setText(_translate("script_widget", "Use mask method"))
        self.label_6.setText(_translate("script_widget", "Select a mask:"))
        self.process_radio_exposure.setText(_translate("script_widget", "Use high exposure"))
        self.label_5.setText(_translate("script_widget", "Select the measurement:"))
        self.label_2.setText(_translate("script_widget", "Reference measurement: "))
        self.label_3.setText(_translate("script_widget", "Background measurement:"))
        self.label_4.setText(_translate("script_widget", "Mask for reduction:"))
        self.process_button_run_data.setText(_translate("script_widget", "Run Data"))
        self.process_button_run_phase.setText(_translate("script_widget", "Run Phase"))
        self.process_button_run_fit.setText(_translate("script_widget", "Run Reduction"))
        self.process_button_run_post.setText(_translate("script_widget", "Run Post"))
        self.process_button_script_data.setText(_translate("script_widget", "Script Data"))
        self.process_button_script_phase.setText(_translate("script_widget", "Script Phase"))
        self.process_button_script_fit.setText(_translate("script_widget", "Script Reduction"))
        self.process_button_script_post.setText(_translate("script_widget", "Script Post"))
        self.script_label_running.setText(_translate("script_widget", "Script running:"))
        self.scrip_label_action.setText(_translate("script_widget", "Action:"))
        self.script_label_action_2.setText(_translate("script_widget", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.process_tab), _translate("script_widget", "Process"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.panel_tab), _translate("script_widget", "Panel"))
        self.script_button_import_gui.setText(_translate("script_widget", "Send to GUI"))
        self.script_button_import_run.setText(_translate("script_widget", "Run"))
        self.script_tabs.setTabText(self.script_tabs.indexOf(self.script_tab_import), _translate("script_widget", "Data import"))
        self.script_button_phase_gui.setText(_translate("script_widget", "Send to GUI"))
        self.script_button_phase_run.setText(_translate("script_widget", "Run"))
        self.script_tabs.setTabText(self.script_tabs.indexOf(self.script_tab_phase), _translate("script_widget", "Phase correction"))
        self.script_button_reduction_gui.setText(_translate("script_widget", "Send to GUI"))
        self.script_button_reduction_run.setText(_translate("script_widget", "Run"))
        self.script_tabs.setTabText(self.script_tabs.indexOf(self.script_tab_reduction), _translate("script_widget", "Reduction"))
        self.script_button_post_run.setText(_translate("script_widget", "Run"))
        self.script_tabs.setTabText(self.script_tabs.indexOf(self.tab), _translate("script_widget", "Post process"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.script_tab), _translate("script_widget", "Scripts"))
        self.groupBox.setTitle(_translate("script_widget", "Data"))
        self.label_11.setText(_translate("script_widget", "Select x"))
        self.process_tree_x.setSortingEnabled(True)
        self.label_10.setText(_translate("script_widget", "Select y"))
        self.process_tree_y.setSortingEnabled(True)
        self.label_8.setText(_translate("script_widget", "Select error"))
        self.process_tree_error.setSortingEnabled(True)
        self.process_button_echo_fit.setText(_translate("script_widget", "Echo Fit"))
        self.process_button_gamma.setText(_translate("script_widget", "Gamma"))
        self.groupBox_3.setTitle(_translate("script_widget", "Plot"))
        self.process_tree_plot.setSortingEnabled(False)
        self.process_button_plot_add.setText(_translate("script_widget", "+"))
        self.process_button_plot_remove.setText(_translate("script_widget", "-"))
        self.process_button_plot_reset.setText(_translate("script_widget", "Reset"))
        self.process_check_offset.setText(_translate("script_widget", "Offset"))
        self.process_check_log_x.setText(_translate("script_widget", "Log x"))
        self.process_check_log_y.setText(_translate("script_widget", "Log y"))
        self.process_button_plot_hide.setText(_translate("script_widget", "Hide"))
        self.process_button_plot_plot.setText(_translate("script_widget", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.result_tab), _translate("script_widget", "Results"))

