# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_data_import.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_data_import(object):
    def setupUi(self, data_import):
        data_import.setObjectName("data_import")
        data_import.resize(1192, 887)
        data_import.setStyleSheet("#data_import{background-color: rgb(179, 179, 179);}\n"
"QGroupBox::title{color:rgb(0, 0, 0)}\n"
"QLabel{color:rgb(0, 0, 0)}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(data_import)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.data_group_dialog = QtWidgets.QGroupBox(data_import)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_group_dialog.sizePolicy().hasHeightForWidth())
        self.data_group_dialog.setSizePolicy(sizePolicy)
        self.data_group_dialog.setMinimumSize(QtCore.QSize(0, 0))
        self.data_group_dialog.setMaximumSize(QtCore.QSize(300, 16777215))
        self.data_group_dialog.setObjectName("data_group_dialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.data_group_dialog)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.data_label_meta = QtWidgets.QLabel(self.data_group_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_label_meta.sizePolicy().hasHeightForWidth())
        self.data_label_meta.setSizePolicy(sizePolicy)
        self.data_label_meta.setObjectName("data_label_meta")
        self.verticalLayout_12.addWidget(self.data_label_meta)
        self.data_list_meta = QtWidgets.QListWidget(self.data_group_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_list_meta.sizePolicy().hasHeightForWidth())
        self.data_list_meta.setSizePolicy(sizePolicy)
        self.data_list_meta.setMinimumSize(QtCore.QSize(0, 30))
        self.data_list_meta.setSizeIncrement(QtCore.QSize(0, 0))
        self.data_list_meta.setAcceptDrops(True)
        self.data_list_meta.setLineWidth(0)
        self.data_list_meta.setAutoScrollMargin(10)
        self.data_list_meta.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.data_list_meta.setObjectName("data_list_meta")
        self.verticalLayout_12.addWidget(self.data_list_meta)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.data_button_meta_all = QtWidgets.QPushButton(self.data_group_dialog)
        self.data_button_meta_all.setObjectName("data_button_meta_all")
        self.horizontalLayout_7.addWidget(self.data_button_meta_all)
        self.data_button_meta_remove = QtWidgets.QPushButton(self.data_group_dialog)
        self.data_button_meta_remove.setObjectName("data_button_meta_remove")
        self.horizontalLayout_7.addWidget(self.data_button_meta_remove)
        self.data_button_meta_add = QtWidgets.QPushButton(self.data_group_dialog)
        self.data_button_meta_add.setObjectName("data_button_meta_add")
        self.horizontalLayout_7.addWidget(self.data_button_meta_add)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.data_label_files = QtWidgets.QLabel(self.data_group_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_label_files.sizePolicy().hasHeightForWidth())
        self.data_label_files.setSizePolicy(sizePolicy)
        self.data_label_files.setObjectName("data_label_files")
        self.verticalLayout_10.addWidget(self.data_label_files)
        self.add_custome_file = QtWidgets.QHBoxLayout()
        self.add_custome_file.setContentsMargins(-1, 0, -1, -1)
        self.add_custome_file.setObjectName("add_custome_file")
        self.verticalLayout_10.addLayout(self.add_custome_file)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.data_button_files_reset = QtWidgets.QPushButton(self.data_group_dialog)
        self.data_button_files_reset.setObjectName("data_button_files_reset")
        self.horizontalLayout_8.addWidget(self.data_button_files_reset)
        self.data_button_files_remove = QtWidgets.QPushButton(self.data_group_dialog)
        self.data_button_files_remove.setObjectName("data_button_files_remove")
        self.horizontalLayout_8.addWidget(self.data_button_files_remove)
        self.data_button_files_add = QtWidgets.QPushButton(self.data_group_dialog)
        self.data_button_files_add.setObjectName("data_button_files_add")
        self.horizontalLayout_8.addWidget(self.data_button_files_add)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.data_label_prev = QtWidgets.QLabel(self.data_group_dialog)
        self.data_label_prev.setObjectName("data_label_prev")
        self.horizontalLayout_4.addWidget(self.data_label_prev)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.data_button_prev = QtWidgets.QPushButton(self.data_group_dialog)
        self.data_button_prev.setObjectName("data_button_prev")
        self.horizontalLayout_4.addWidget(self.data_button_prev)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.data_widget_graph = QtWidgets.QWidget(self.data_group_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_widget_graph.sizePolicy().hasHeightForWidth())
        self.data_widget_graph.setSizePolicy(sizePolicy)
        self.data_widget_graph.setMinimumSize(QtCore.QSize(268, 250))
        self.data_widget_graph.setMaximumSize(QtCore.QSize(250, 250))
        self.data_widget_graph.setSizeIncrement(QtCore.QSize(0, 1))
        self.data_widget_graph.setBaseSize(QtCore.QSize(268, 250))
        self.data_widget_graph.setObjectName("data_widget_graph")
        self.verticalLayout_13.addWidget(self.data_widget_graph)
        self.verticalLayout.addLayout(self.verticalLayout_13)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.data_button_populate = QtWidgets.QPushButton(self.data_group_dialog)
        self.data_button_populate.setDefault(True)
        self.data_button_populate.setObjectName("data_button_populate")
        self.horizontalLayout_2.addWidget(self.data_button_populate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.data_group_dialog)
        self.data_group_loaded = QtWidgets.QGroupBox(data_import)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_group_loaded.sizePolicy().hasHeightForWidth())
        self.data_group_loaded.setSizePolicy(sizePolicy)
        self.data_group_loaded.setObjectName("data_group_loaded")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.data_group_loaded)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.data_list_loaded = QtWidgets.QListWidget(self.data_group_loaded)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_list_loaded.sizePolicy().hasHeightForWidth())
        self.data_list_loaded.setSizePolicy(sizePolicy)
        self.data_list_loaded.setSizeIncrement(QtCore.QSize(2, 0))
        self.data_list_loaded.setAcceptDrops(True)
        self.data_list_loaded.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.data_list_loaded.setLineWidth(0)
        self.data_list_loaded.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.data_list_loaded.setViewMode(QtWidgets.QListView.ListMode)
        self.data_list_loaded.setSelectionRectVisible(True)
        self.data_list_loaded.setObjectName("data_list_loaded")
        self.verticalLayout_2.addWidget(self.data_list_loaded)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.data_button_add_object = QtWidgets.QPushButton(self.data_group_loaded)
        self.data_button_add_object.setObjectName("data_button_add_object")
        self.horizontalLayout_3.addWidget(self.data_button_add_object)
        self.data_button_remove_object = QtWidgets.QPushButton(self.data_group_loaded)
        self.data_button_remove_object.setObjectName("data_button_remove_object")
        self.horizontalLayout_3.addWidget(self.data_button_remove_object)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.data_group_loaded)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.data_input_foils = QtWidgets.QLineEdit(self.data_group_loaded)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_input_foils.sizePolicy().hasHeightForWidth())
        self.data_input_foils.setSizePolicy(sizePolicy)
        self.data_input_foils.setMinimumSize(QtCore.QSize(50, 0))
        self.data_input_foils.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_input_foils.setBaseSize(QtCore.QSize(50, 0))
        self.data_input_foils.setMaxLength(32763)
        self.data_input_foils.setAlignment(QtCore.Qt.AlignCenter)
        self.data_input_foils.setObjectName("data_input_foils")
        self.horizontalLayout_3.addWidget(self.data_input_foils)
        self.data_input_time_channel = QtWidgets.QLineEdit(self.data_group_loaded)
        self.data_input_time_channel.setMinimumSize(QtCore.QSize(50, 0))
        self.data_input_time_channel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_input_time_channel.setSizeIncrement(QtCore.QSize(50, 0))
        self.data_input_time_channel.setBaseSize(QtCore.QSize(50, 0))
        self.data_input_time_channel.setAlignment(QtCore.Qt.AlignCenter)
        self.data_input_time_channel.setObjectName("data_input_time_channel")
        self.horizontalLayout_3.addWidget(self.data_input_time_channel)
        self.data_input_pix_x = QtWidgets.QLineEdit(self.data_group_loaded)
        self.data_input_pix_x.setMinimumSize(QtCore.QSize(50, 0))
        self.data_input_pix_x.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_input_pix_x.setBaseSize(QtCore.QSize(50, 0))
        self.data_input_pix_x.setAlignment(QtCore.Qt.AlignCenter)
        self.data_input_pix_x.setObjectName("data_input_pix_x")
        self.horizontalLayout_3.addWidget(self.data_input_pix_x)
        self.data_input_pix_y = QtWidgets.QLineEdit(self.data_group_loaded)
        self.data_input_pix_y.setMinimumSize(QtCore.QSize(50, 0))
        self.data_input_pix_y.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_input_pix_y.setBaseSize(QtCore.QSize(50, 0))
        self.data_input_pix_y.setAlignment(QtCore.Qt.AlignCenter)
        self.data_input_pix_y.setObjectName("data_input_pix_y")
        self.horizontalLayout_3.addWidget(self.data_input_pix_y)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.data_button_validate = QtWidgets.QPushButton(self.data_group_loaded)
        self.data_button_validate.setDefault(True)
        self.data_button_validate.setObjectName("data_button_validate")
        self.horizontalLayout_3.addWidget(self.data_button_validate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.data_group_loaded)

        self.retranslateUi(data_import)
        QtCore.QMetaObject.connectSlotsByName(data_import)

    def retranslateUi(self, data_import):
        _translate = QtCore.QCoreApplication.translate
        data_import.setWindowTitle(_translate("data_import", "Form"))
        self.data_group_dialog.setTitle(_translate("data_import", "Loading dialog"))
        self.data_label_meta.setText(_translate("data_import", "Metadata keywords:"))
        self.data_button_meta_all.setToolTip(_translate("data_import", "Porpagate the current metadata to all elements"))
        self.data_button_meta_all.setText(_translate("data_import", "All"))
        self.data_button_meta_remove.setToolTip(_translate("data_import", "Remove current metadata"))
        self.data_button_meta_remove.setText(_translate("data_import", "Remove"))
        self.data_button_meta_add.setToolTip(_translate("data_import", "add an element to the metadata"))
        self.data_button_meta_add.setText(_translate("data_import", "Add"))
        self.data_label_files.setText(_translate("data_import", "Files:"))
        self.data_button_files_reset.setToolTip(_translate("data_import", "Reset the list"))
        self.data_button_files_reset.setText(_translate("data_import", "Reset"))
        self.data_button_files_remove.setToolTip(_translate("data_import", "Remove the selected file"))
        self.data_button_files_remove.setText(_translate("data_import", "Remove"))
        self.data_button_files_add.setToolTip(_translate("data_import", "Add a file ..."))
        self.data_button_files_add.setText(_translate("data_import", "Add"))
        self.data_label_prev.setText(_translate("data_import", "Preview:"))
        self.data_button_prev.setToolTip(_translate("data_import", "fide the preview element"))
        self.data_button_prev.setText(_translate("data_import", "hide"))
        self.data_button_populate.setToolTip(_translate("data_import", "Populate the data element with the current input"))
        self.data_button_populate.setText(_translate("data_import", "Populate this dataset"))
        self.data_group_loaded.setTitle(_translate("data_import", "Loaded data"))
        self.data_button_add_object.setToolTip(_translate("data_import", "Add an element to the dataset"))
        self.data_button_add_object.setText(_translate("data_import", "+"))
        self.data_button_remove_object.setToolTip(_translate("data_import", "Remove the currently selected element"))
        self.data_button_remove_object.setText(_translate("data_import", "-"))
        self.label.setText(_translate("data_import", "Dimensions"))
        self.data_input_foils.setToolTip(_translate("data_import", "Number of foils"))
        self.data_input_foils.setText(_translate("data_import", "8"))
        self.data_input_time_channel.setToolTip(_translate("data_import", "Number of time channels"))
        self.data_input_time_channel.setText(_translate("data_import", "16"))
        self.data_input_pix_x.setToolTip(_translate("data_import", "pixels along x"))
        self.data_input_pix_x.setText(_translate("data_import", "128"))
        self.data_input_pix_y.setToolTip(_translate("data_import", "pixels along y"))
        self.data_input_pix_y.setText(_translate("data_import", "128"))
        self.data_button_validate.setToolTip(_translate("data_import", "Populate the data element with the current input"))
        self.data_button_validate.setText(_translate("data_import", "Validate"))

