# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MIEZETool(object):
    def setupUi(self, MIEZETool):
        MIEZETool.setObjectName("MIEZETool")
        MIEZETool.resize(1234, 892)
        MIEZETool.setStyleSheet("")
        self.main_widget = QtWidgets.QWidget(MIEZETool)
        self.main_widget.setStyleSheet("")
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(100, 0))
        self.widget.setStyleSheet("#widget{\n"
"background-color: rgb(64, 66, 68);}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(35)
        self.verticalLayout.setObjectName("verticalLayout")
        self.env_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.env_button.sizePolicy().hasHeightForWidth())
        self.env_button.setSizePolicy(sizePolicy)
        self.env_button.setMinimumSize(QtCore.QSize(64, 40))
        self.env_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.env_button.setAutoFillBackground(False)
        self.env_button.setStyleSheet("#env_button { \n"
"background-color: transparent; \n"
"qproperty-icon: url(:/Ressources/env_raw.ico); \n"
"background: none; \n"
"border: none; \n"
"background-repeat: none; \n"
"} \n"
"#env_button:checked { \n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.50033, fy:0.505682,stop:0 rgba(94, 0, 255, 255), stop:1 rgb(64, 66, 68) );\n"
"}\n"
"\n"
"")
        self.env_button.setText("")
        self.env_button.setIconSize(QtCore.QSize(45, 64))
        self.env_button.setCheckable(True)
        self.env_button.setChecked(True)
        self.env_button.setAutoRepeat(False)
        self.env_button.setAutoExclusive(False)
        self.env_button.setAutoDefault(False)
        self.env_button.setFlat(False)
        self.env_button.setObjectName("env_button")
        self.verticalLayout.addWidget(self.env_button)
        self.data_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_button.sizePolicy().hasHeightForWidth())
        self.data_button.setSizePolicy(sizePolicy)
        self.data_button.setMinimumSize(QtCore.QSize(64, 40))
        self.data_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.data_button.setAutoFillBackground(False)
        self.data_button.setStyleSheet("#data_button { \n"
"background-color: transparent; \n"
"qproperty-icon: url(:/Ressources/data.ico); \n"
"background: none; \n"
"border: none; \n"
"background-repeat: none; \n"
"} \n"
"#data_button:checked { \n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.50033, fy:0.505682,stop:0 rgba(94, 0, 255, 255), stop:1 rgb(64, 66, 68) );\n"
"}")
        self.data_button.setText("")
        self.data_button.setIconSize(QtCore.QSize(45, 64))
        self.data_button.setCheckable(True)
        self.data_button.setChecked(True)
        self.data_button.setAutoRepeat(False)
        self.data_button.setAutoExclusive(False)
        self.data_button.setAutoDefault(False)
        self.data_button.setFlat(False)
        self.data_button.setObjectName("data_button")
        self.verticalLayout.addWidget(self.data_button)
        self.mask_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_button.sizePolicy().hasHeightForWidth())
        self.mask_button.setSizePolicy(sizePolicy)
        self.mask_button.setMinimumSize(QtCore.QSize(64, 40))
        self.mask_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.mask_button.setAutoFillBackground(False)
        self.mask_button.setStyleSheet("#mask_button { \n"
"background-color: transparent; \n"
"qproperty-icon: url(:/Ressources/mask.ico); \n"
"background: none; \n"
"border: none; \n"
"background-repeat: none; \n"
"} \n"
"#mask_button:checked { \n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.50033, fy:0.505682,stop:0 rgba(94, 0, 255, 255), stop:1 rgb(64, 66, 68) );\n"
"}\n"
"")
        self.mask_button.setText("")
        self.mask_button.setIconSize(QtCore.QSize(45, 64))
        self.mask_button.setCheckable(True)
        self.mask_button.setChecked(True)
        self.mask_button.setAutoRepeat(False)
        self.mask_button.setAutoExclusive(False)
        self.mask_button.setAutoDefault(False)
        self.mask_button.setFlat(False)
        self.mask_button.setObjectName("mask_button")
        self.verticalLayout.addWidget(self.mask_button)
        self.script_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.script_button.sizePolicy().hasHeightForWidth())
        self.script_button.setSizePolicy(sizePolicy)
        self.script_button.setMinimumSize(QtCore.QSize(64, 40))
        self.script_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.script_button.setAutoFillBackground(False)
        self.script_button.setStyleSheet("#script_button { \n"
"background-color: transparent; \n"
"qproperty-icon: url(:/Ressources/script.ico); \n"
"background: none; \n"
"border: none; \n"
"background-repeat: none; \n"
"} \n"
"#script_button:checked { \n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.50033, fy:0.505682,stop:0 rgba(94, 0, 255, 255), stop:1 rgb(64, 66, 68) );\n"
"}\n"
"")
        self.script_button.setText("")
        self.script_button.setIconSize(QtCore.QSize(45, 64))
        self.script_button.setCheckable(True)
        self.script_button.setChecked(True)
        self.script_button.setAutoRepeat(False)
        self.script_button.setAutoExclusive(False)
        self.script_button.setAutoDefault(False)
        self.script_button.setFlat(False)
        self.script_button.setObjectName("script_button")
        self.verticalLayout.addWidget(self.script_button)
        self.save_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setMinimumSize(QtCore.QSize(64, 40))
        self.save_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.save_button.setAutoFillBackground(False)
        self.save_button.setStyleSheet("#save_button { \n"
"background-color: transparent; \n"
"qproperty-icon: url(:/Ressources/save.ico); \n"
"background: none; \n"
"border: none; \n"
"background-repeat: none; \n"
"} \n"
"#save_button:checked { \n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.50033, fy:0.505682,stop:0 rgba(94, 0, 255, 255), stop:1 rgb(64, 66, 68) );\n"
"}\n"
"")
        self.save_button.setText("")
        self.save_button.setIconSize(QtCore.QSize(45, 64))
        self.save_button.setCheckable(True)
        self.save_button.setChecked(True)
        self.save_button.setAutoRepeat(False)
        self.save_button.setAutoExclusive(False)
        self.save_button.setAutoDefault(False)
        self.save_button.setFlat(False)
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_line_progress_0 = QtWidgets.QFrame(self.widget)
        self.main_line_progress_0.setFrameShape(QtWidgets.QFrame.HLine)
        self.main_line_progress_0.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.main_line_progress_0.setObjectName("main_line_progress_0")
        self.verticalLayout_3.addWidget(self.main_line_progress_0)
        self.main_label_progress_0 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_label_progress_0.sizePolicy().hasHeightForWidth())
        self.main_label_progress_0.setSizePolicy(sizePolicy)
        self.main_label_progress_0.setMinimumSize(QtCore.QSize(75, 0))
        self.main_label_progress_0.setMaximumSize(QtCore.QSize(64, 16777215))
        self.main_label_progress_0.setStyleSheet("#main_label_progress_0{color: rgb(179, 179, 179);}")
        self.main_label_progress_0.setAlignment(QtCore.Qt.AlignCenter)
        self.main_label_progress_0.setWordWrap(True)
        self.main_label_progress_0.setObjectName("main_label_progress_0")
        self.verticalLayout_3.addWidget(self.main_label_progress_0)
        self.main_bar_progress = QtWidgets.QProgressBar(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_bar_progress.sizePolicy().hasHeightForWidth())
        self.main_bar_progress.setSizePolicy(sizePolicy)
        self.main_bar_progress.setMinimumSize(QtCore.QSize(75, 0))
        self.main_bar_progress.setMaximumSize(QtCore.QSize(75, 16777215))
        self.main_bar_progress.setStyleSheet("")
        self.main_bar_progress.setProperty("value", 24)
        self.main_bar_progress.setAlignment(QtCore.Qt.AlignCenter)
        self.main_bar_progress.setObjectName("main_bar_progress")
        self.verticalLayout_3.addWidget(self.main_bar_progress)
        self.main_label_progress_1 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_label_progress_1.sizePolicy().hasHeightForWidth())
        self.main_label_progress_1.setSizePolicy(sizePolicy)
        self.main_label_progress_1.setMinimumSize(QtCore.QSize(75, 0))
        self.main_label_progress_1.setMaximumSize(QtCore.QSize(75, 16777215))
        self.main_label_progress_1.setStyleSheet("#main_label_progress_1{color: rgb(179, 179, 179);}")
        self.main_label_progress_1.setAlignment(QtCore.Qt.AlignCenter)
        self.main_label_progress_1.setWordWrap(True)
        self.main_label_progress_1.setObjectName("main_label_progress_1")
        self.verticalLayout_3.addWidget(self.main_label_progress_1)
        self.main_line_progress_1 = QtWidgets.QFrame(self.widget)
        self.main_line_progress_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.main_line_progress_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.main_line_progress_1.setObjectName("main_line_progress_1")
        self.verticalLayout_3.addWidget(self.main_line_progress_1)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("#label{color: \"grey\";}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addWidget(self.widget)
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.horizontalLayout.addLayout(self.main_layout)
        MIEZETool.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(MIEZETool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1234, 34))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCurrent_Environmen = QtWidgets.QMenu(self.menubar)
        self.menuCurrent_Environmen.setObjectName("menuCurrent_Environmen")
        self.menuData = QtWidgets.QMenu(self.menuCurrent_Environmen)
        self.menuData.setObjectName("menuData")
        self.menuScripts = QtWidgets.QMenu(self.menuCurrent_Environmen)
        self.menuScripts.setObjectName("menuScripts")
        self.menuRun = QtWidgets.QMenu(self.menuScripts)
        self.menuRun.setObjectName("menuRun")
        self.menuMask = QtWidgets.QMenu(self.menuCurrent_Environmen)
        self.menuMask.setObjectName("menuMask")
        MIEZETool.setMenuBar(self.menubar)
        self.actionAddEnv = QtWidgets.QAction(MIEZETool)
        self.actionAddEnv.setObjectName("actionAddEnv")
        self.actionAdd_Data = QtWidgets.QAction(MIEZETool)
        self.actionAdd_Data.setObjectName("actionAdd_Data")
        self.actionLoad_Data = QtWidgets.QAction(MIEZETool)
        self.actionLoad_Data.setObjectName("actionLoad_Data")
        self.actionCompute = QtWidgets.QAction(MIEZETool)
        self.actionCompute.setObjectName("actionCompute")
        self.actionResult = QtWidgets.QAction(MIEZETool)
        self.actionResult.setObjectName("actionResult")
        self.actionRemoveEnv = QtWidgets.QAction(MIEZETool)
        self.actionRemoveEnv.setObjectName("actionRemoveEnv")
        self.actionLoad_Session = QtWidgets.QAction(MIEZETool)
        self.actionLoad_Session.setObjectName("actionLoad_Session")
        self.actionSave_Session = QtWidgets.QAction(MIEZETool)
        self.actionSave_Session.setObjectName("actionSave_Session")
        self.actionQuit = QtWidgets.QAction(MIEZETool)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLoad_Script = QtWidgets.QAction(MIEZETool)
        self.actionLoad_Script.setObjectName("actionLoad_Script")
        self.actionSave_Script = QtWidgets.QAction(MIEZETool)
        self.actionSave_Script.setObjectName("actionSave_Script")
        self.actionDelete = QtWidgets.QAction(MIEZETool)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSave_2 = QtWidgets.QAction(MIEZETool)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionJump_to = QtWidgets.QAction(MIEZETool)
        self.actionJump_to.setObjectName("actionJump_to")
        self.actionAdd_element = QtWidgets.QAction(MIEZETool)
        self.actionAdd_element.setObjectName("actionAdd_element")
        self.actionRemove_element = QtWidgets.QAction(MIEZETool)
        self.actionRemove_element.setObjectName("actionRemove_element")
        self.actionLoad_from_file = QtWidgets.QAction(MIEZETool)
        self.actionLoad_from_file.setObjectName("actionLoad_from_file")
        self.actionSave_to_file = QtWidgets.QAction(MIEZETool)
        self.actionSave_to_file.setObjectName("actionSave_to_file")
        self.actionGenerate = QtWidgets.QAction(MIEZETool)
        self.actionGenerate.setObjectName("actionGenerate")
        self.actionImport = QtWidgets.QAction(MIEZETool)
        self.actionImport.setObjectName("actionImport")
        self.actionPhase = QtWidgets.QAction(MIEZETool)
        self.actionPhase.setObjectName("actionPhase")
        self.actionReduction = QtWidgets.QAction(MIEZETool)
        self.actionReduction.setObjectName("actionReduction")
        self.actionVisual = QtWidgets.QAction(MIEZETool)
        self.actionVisual.setObjectName("actionVisual")
        self.actionAll = QtWidgets.QAction(MIEZETool)
        self.actionAll.setObjectName("actionAll")
        self.actionLoadScript = QtWidgets.QAction(MIEZETool)
        self.actionLoadScript.setObjectName("actionLoadScript")
        self.actionSaveScript = QtWidgets.QAction(MIEZETool)
        self.actionSaveScript.setObjectName("actionSaveScript")
        self.actionSaveMask = QtWidgets.QAction(MIEZETool)
        self.actionSaveMask.setObjectName("actionSaveMask")
        self.actionLoadMask = QtWidgets.QAction(MIEZETool)
        self.actionLoadMask.setObjectName("actionLoadMask")
        self.actionSaveMaskAll = QtWidgets.QAction(MIEZETool)
        self.actionSaveMaskAll.setObjectName("actionSaveMaskAll")
        self.actionLoadMaskAll = QtWidgets.QAction(MIEZETool)
        self.actionLoadMaskAll.setObjectName("actionLoadMaskAll")
        self.menuFile.addAction(self.actionAddEnv)
        self.menuFile.addAction(self.actionRemoveEnv)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Session)
        self.menuFile.addAction(self.actionSave_Session)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuData.addAction(self.actionJump_to)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionAdd_element)
        self.menuData.addAction(self.actionRemove_element)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionLoad_from_file)
        self.menuData.addAction(self.actionSave_to_file)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionGenerate)
        self.menuRun.addAction(self.actionImport)
        self.menuRun.addAction(self.actionPhase)
        self.menuRun.addAction(self.actionReduction)
        self.menuRun.addAction(self.actionVisual)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionAll)
        self.menuScripts.addAction(self.menuRun.menuAction())
        self.menuScripts.addSeparator()
        self.menuScripts.addAction(self.actionLoadScript)
        self.menuScripts.addAction(self.actionSaveScript)
        self.menuMask.addAction(self.actionSaveMask)
        self.menuMask.addAction(self.actionLoadMask)
        self.menuMask.addSeparator()
        self.menuMask.addAction(self.actionSaveMaskAll)
        self.menuMask.addAction(self.actionLoadMaskAll)
        self.menuCurrent_Environmen.addAction(self.menuData.menuAction())
        self.menuCurrent_Environmen.addAction(self.menuScripts.menuAction())
        self.menuCurrent_Environmen.addAction(self.menuMask.menuAction())
        self.menuCurrent_Environmen.addSeparator()
        self.menuCurrent_Environmen.addAction(self.actionSave_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCurrent_Environmen.menuAction())

        self.retranslateUi(MIEZETool)
        QtCore.QMetaObject.connectSlotsByName(MIEZETool)

    def retranslateUi(self, MIEZETool):
        _translate = QtCore.QCoreApplication.translate
        MIEZETool.setWindowTitle(_translate("MIEZETool", "MIEZE Tool"))
        self.main_label_progress_0.setText(_translate("MIEZETool", "TextLabel"))
        self.main_label_progress_1.setText(_translate("MIEZETool", "TextLabel"))
        self.label.setText(_translate("MIEZETool", "v 0.0.1"))
        self.menuFile.setTitle(_translate("MIEZETool", "&File"))
        self.menuCurrent_Environmen.setTitle(_translate("MIEZETool", "&Current Env."))
        self.menuData.setTitle(_translate("MIEZETool", "&Data"))
        self.menuScripts.setTitle(_translate("MIEZETool", "&Scripts"))
        self.menuRun.setTitle(_translate("MIEZETool", "&Run"))
        self.menuMask.setTitle(_translate("MIEZETool", "&Mask"))
        self.actionAddEnv.setText(_translate("MIEZETool", "&Add Environment"))
        self.actionAdd_Data.setText(_translate("MIEZETool", "Add Data"))
        self.actionLoad_Data.setText(_translate("MIEZETool", "Load Data"))
        self.actionCompute.setText(_translate("MIEZETool", "Compute"))
        self.actionResult.setText(_translate("MIEZETool", "Result ..."))
        self.actionRemoveEnv.setText(_translate("MIEZETool", "&Remove Environment"))
        self.actionLoad_Session.setText(_translate("MIEZETool", "&Quick Load Session"))
        self.actionSave_Session.setText(_translate("MIEZETool", "Q&uick Save Session"))
        self.actionQuit.setText(_translate("MIEZETool", "Qu&it"))
        self.actionLoad_Script.setText(_translate("MIEZETool", "Masks"))
        self.actionSave_Script.setText(_translate("MIEZETool", "Results"))
        self.actionDelete.setText(_translate("MIEZETool", "Remove"))
        self.actionSave_2.setText(_translate("MIEZETool", "Sa&ve"))
        self.actionJump_to.setText(_translate("MIEZETool", "&Jump to ..."))
        self.actionAdd_element.setText(_translate("MIEZETool", "&Add element"))
        self.actionAdd_element.setShortcut(_translate("MIEZETool", "Ctrl++"))
        self.actionRemove_element.setText(_translate("MIEZETool", "&Remove element"))
        self.actionRemove_element.setShortcut(_translate("MIEZETool", "Ctrl+-"))
        self.actionLoad_from_file.setText(_translate("MIEZETool", "&Load from file"))
        self.actionLoad_from_file.setShortcut(_translate("MIEZETool", "Ctrl+K"))
        self.actionSave_to_file.setText(_translate("MIEZETool", "&Save to file"))
        self.actionSave_to_file.setShortcut(_translate("MIEZETool", "Ctrl+L"))
        self.actionGenerate.setText(_translate("MIEZETool", "&Generate"))
        self.actionGenerate.setShortcut(_translate("MIEZETool", "Ctrl+G"))
        self.actionImport.setText(_translate("MIEZETool", "&Import"))
        self.actionImport.setShortcut(_translate("MIEZETool", "Ctrl+1"))
        self.actionPhase.setText(_translate("MIEZETool", "&Phase"))
        self.actionPhase.setShortcut(_translate("MIEZETool", "Ctrl+2"))
        self.actionReduction.setText(_translate("MIEZETool", "&Reduction"))
        self.actionReduction.setShortcut(_translate("MIEZETool", "Ctrl+3"))
        self.actionVisual.setText(_translate("MIEZETool", "&Visual"))
        self.actionVisual.setShortcut(_translate("MIEZETool", "Ctrl+4"))
        self.actionAll.setText(_translate("MIEZETool", "&All"))
        self.actionAll.setShortcut(_translate("MIEZETool", "Ctrl+0"))
        self.actionLoadScript.setText(_translate("MIEZETool", "&Load from file"))
        self.actionLoadScript.setShortcut(_translate("MIEZETool", "Ctrl+D"))
        self.actionSaveScript.setText(_translate("MIEZETool", "&Save to file"))
        self.actionSaveScript.setShortcut(_translate("MIEZETool", "Ctrl+E"))
        self.actionSaveMask.setText(_translate("MIEZETool", "&Save current to file ..."))
        self.actionLoadMask.setText(_translate("MIEZETool", "&Load current from file ..."))
        self.actionSaveMaskAll.setText(_translate("MIEZETool", "Sa&ve all to file ..."))
        self.actionLoadMaskAll.setText(_translate("MIEZETool", "Load all &from file ..."))

