# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mask_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mask_widget(object):
    def setupUi(self, mask_widget):
        mask_widget.setObjectName("mask_widget")
        mask_widget.resize(400, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mask_widget.sizePolicy().hasHeightForWidth())
        mask_widget.setSizePolicy(sizePolicy)
        mask_widget.setMinimumSize(QtCore.QSize(400, 150))
        mask_widget.setMaximumSize(QtCore.QSize(400, 250))
        mask_widget.setBaseSize(QtCore.QSize(0, 250))
        mask_widget.setStyleSheet("#mask_widget{\n"
"background-color: rgb(255, 255, 255);}\n"
"\n"
"#mask_widget:focus{\n"
"background-color: rgb(220, 220, 220);\n"
"\n"
"}\n"
"\n"
"")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(mask_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mask_box_parent = QtWidgets.QGroupBox(mask_widget)
        self.mask_box_parent.setMinimumSize(QtCore.QSize(0, 150))
        self.mask_box_parent.setMaximumSize(QtCore.QSize(16777215, 150))
        self.mask_box_parent.setStyleSheet("#mask_widget{background-color: rgb(179, 179, 179);}")
        self.mask_box_parent.setObjectName("mask_box_parent")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.mask_box_parent)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mask_label_type = QtWidgets.QLabel(self.mask_box_parent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_label_type.sizePolicy().hasHeightForWidth())
        self.mask_label_type.setSizePolicy(sizePolicy)
        self.mask_label_type.setMinimumSize(QtCore.QSize(50, 0))
        self.mask_label_type.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_label_type.setFont(font)
        self.mask_label_type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mask_label_type.setObjectName("mask_label_type")
        self.horizontalLayout_3.addWidget(self.mask_label_type)
        self.mask_combo_type = QtWidgets.QComboBox(self.mask_box_parent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_combo_type.sizePolicy().hasHeightForWidth())
        self.mask_combo_type.setSizePolicy(sizePolicy)
        self.mask_combo_type.setMinimumSize(QtCore.QSize(110, 0))
        self.mask_combo_type.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mask_combo_type.setObjectName("mask_combo_type")
        self.horizontalLayout_3.addWidget(self.mask_combo_type)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mask_label_position = QtWidgets.QLabel(self.mask_box_parent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_label_position.sizePolicy().hasHeightForWidth())
        self.mask_label_position.setSizePolicy(sizePolicy)
        self.mask_label_position.setMinimumSize(QtCore.QSize(50, 0))
        self.mask_label_position.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_label_position.setFont(font)
        self.mask_label_position.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mask_label_position.setObjectName("mask_label_position")
        self.horizontalLayout_4.addWidget(self.mask_label_position)
        self.mask_spin_position_0 = QtWidgets.QSpinBox(self.mask_box_parent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_spin_position_0.sizePolicy().hasHeightForWidth())
        self.mask_spin_position_0.setSizePolicy(sizePolicy)
        self.mask_spin_position_0.setMinimumSize(QtCore.QSize(50, 0))
        self.mask_spin_position_0.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_spin_position_0.setFont(font)
        self.mask_spin_position_0.setObjectName("mask_spin_position_0")
        self.horizontalLayout_4.addWidget(self.mask_spin_position_0)
        self.mask_spin_position_1 = QtWidgets.QSpinBox(self.mask_box_parent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_spin_position_1.sizePolicy().hasHeightForWidth())
        self.mask_spin_position_1.setSizePolicy(sizePolicy)
        self.mask_spin_position_1.setMinimumSize(QtCore.QSize(50, 0))
        self.mask_spin_position_1.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_spin_position_1.setFont(font)
        self.mask_spin_position_1.setObjectName("mask_spin_position_1")
        self.horizontalLayout_4.addWidget(self.mask_spin_position_1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mask_label_angle = QtWidgets.QLabel(self.mask_box_parent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_label_angle.sizePolicy().hasHeightForWidth())
        self.mask_label_angle.setSizePolicy(sizePolicy)
        self.mask_label_angle.setMinimumSize(QtCore.QSize(50, 0))
        self.mask_label_angle.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_label_angle.setFont(font)
        self.mask_label_angle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mask_label_angle.setObjectName("mask_label_angle")
        self.horizontalLayout_8.addWidget(self.mask_label_angle)
        self.mask_spin_angle = QtWidgets.QSpinBox(self.mask_box_parent)
        self.mask_spin_angle.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_spin_angle.setFont(font)
        self.mask_spin_angle.setObjectName("mask_spin_angle")
        self.horizontalLayout_8.addWidget(self.mask_spin_angle)
        spacerItem = QtWidgets.QSpacerItem(53, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.mask_box_parent)
        self.line.setLineWidth(3)
        self.line.setMidLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_12.addWidget(self.line)
        self.mask_layout_para_grid = QtWidgets.QGridLayout()
        self.mask_layout_para_grid.setContentsMargins(5, 5, 5, 5)
        self.mask_layout_para_grid.setObjectName("mask_layout_para_grid")
        self.horizontalLayout_12.addLayout(self.mask_layout_para_grid)
        self.verticalLayout_3.addWidget(self.mask_box_parent)
        self.mask_box_child = QtWidgets.QGroupBox(mask_widget)
        self.mask_box_child.setMaximumSize(QtCore.QSize(16777215, 100))
        self.mask_box_child.setStyleSheet("#mask_widget{background-color: rgb(179, 179, 179);}")
        self.mask_box_child.setObjectName("mask_box_child")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.mask_box_child)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.mask_label_type_child = QtWidgets.QLabel(self.mask_box_child)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_label_type_child.sizePolicy().hasHeightForWidth())
        self.mask_label_type_child.setSizePolicy(sizePolicy)
        self.mask_label_type_child.setMinimumSize(QtCore.QSize(50, 0))
        self.mask_label_type_child.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_label_type_child.setFont(font)
        self.mask_label_type_child.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mask_label_type_child.setObjectName("mask_label_type_child")
        self.horizontalLayout_19.addWidget(self.mask_label_type_child)
        self.mask_combo_type_child = QtWidgets.QComboBox(self.mask_box_child)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_combo_type_child.sizePolicy().hasHeightForWidth())
        self.mask_combo_type_child.setSizePolicy(sizePolicy)
        self.mask_combo_type_child.setMinimumSize(QtCore.QSize(110, 0))
        self.mask_combo_type_child.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mask_combo_type_child.setObjectName("mask_combo_type_child")
        self.horizontalLayout_19.addWidget(self.mask_combo_type_child)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.mask_label_angle_child = QtWidgets.QLabel(self.mask_box_child)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_label_angle_child.sizePolicy().hasHeightForWidth())
        self.mask_label_angle_child.setSizePolicy(sizePolicy)
        self.mask_label_angle_child.setMinimumSize(QtCore.QSize(50, 0))
        self.mask_label_angle_child.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_label_angle_child.setFont(font)
        self.mask_label_angle_child.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mask_label_angle_child.setObjectName("mask_label_angle_child")
        self.horizontalLayout_21.addWidget(self.mask_label_angle_child)
        self.mask_spin_angle_child = QtWidgets.QSpinBox(self.mask_box_child)
        self.mask_spin_angle_child.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_spin_angle_child.setFont(font)
        self.mask_spin_angle_child.setObjectName("mask_spin_angle_child")
        self.horizontalLayout_21.addWidget(self.mask_spin_angle_child)
        spacerItem1 = QtWidgets.QSpacerItem(53, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_18.addLayout(self.verticalLayout_5)
        self.line_4 = QtWidgets.QFrame(self.mask_box_child)
        self.line_4.setLineWidth(3)
        self.line_4.setMidLineWidth(5)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_18.addWidget(self.line_4)
        self.mask_layout_para_grid_child = QtWidgets.QGridLayout()
        self.mask_layout_para_grid_child.setContentsMargins(5, 5, 5, 5)
        self.mask_layout_para_grid_child.setObjectName("mask_layout_para_grid_child")
        self.horizontalLayout_18.addLayout(self.mask_layout_para_grid_child)
        self.verticalLayout_3.addWidget(self.mask_box_child)

        self.retranslateUi(mask_widget)
        QtCore.QMetaObject.connectSlotsByName(mask_widget)

    def retranslateUi(self, mask_widget):
        _translate = QtCore.QCoreApplication.translate
        mask_widget.setWindowTitle(_translate("mask_widget", "Form"))
        self.mask_box_parent.setTitle(_translate("mask_widget", "Mask element"))
        self.mask_label_type.setText(_translate("mask_widget", "Type: "))
        self.mask_label_position.setText(_translate("mask_widget", "Position: "))
        self.mask_label_angle.setText(_translate("mask_widget", "Angle: "))
        self.mask_box_child.setTitle(_translate("mask_widget", "Child element"))
        self.mask_label_type_child.setText(_translate("mask_widget", "Type: "))
        self.mask_label_angle_child.setText(_translate("mask_widget", "Angle: "))

