# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meta_widget.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_meta_widget(object):
    def setupUi(self, meta_widget):
        meta_widget.setObjectName("meta_widget")
        meta_widget.resize(284, 104)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(meta_widget.sizePolicy().hasHeightForWidth())
        meta_widget.setSizePolicy(sizePolicy)
        meta_widget.setMinimumSize(QtCore.QSize(0, 0))
        meta_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        meta_widget.setSizeIncrement(QtCore.QSize(0, 0))
        meta_widget.setBaseSize(QtCore.QSize(0, 0))
        meta_widget.setStyleSheet("\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(meta_widget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.meta_label_name = QtWidgets.QLabel(meta_widget)
        self.meta_label_name.setMinimumSize(QtCore.QSize(0, 0))
        self.meta_label_name.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.meta_label_name.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.meta_label_name.setFont(font)
        self.meta_label_name.setText("TextLabel")
        self.meta_label_name.setScaledContents(True)
        self.meta_label_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_name.setWordWrap(False)
        self.meta_label_name.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.meta_label_name.setObjectName("meta_label_name")
        self.horizontalLayout_4.addWidget(self.meta_label_name)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.meta_drop_equivalence = QtWidgets.QComboBox(meta_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_drop_equivalence.sizePolicy().hasHeightForWidth())
        self.meta_drop_equivalence.setSizePolicy(sizePolicy)
        self.meta_drop_equivalence.setCurrentText("")
        self.meta_drop_equivalence.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.meta_drop_equivalence.setFrame(True)
        self.meta_drop_equivalence.setObjectName("meta_drop_equivalence")
        self.horizontalLayout.addWidget(self.meta_drop_equivalence)
        self.meta_input_fact = QtWidgets.QLineEdit(meta_widget)
        self.meta_input_fact.setEnabled(True)
        self.meta_input_fact.setMinimumSize(QtCore.QSize(0, 0))
        self.meta_input_fact.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.meta_input_fact.setBaseSize(QtCore.QSize(0, 0))
        self.meta_input_fact.setAcceptDrops(False)
        self.meta_input_fact.setText("")
        self.meta_input_fact.setFrame(True)
        self.meta_input_fact.setObjectName("meta_input_fact")
        self.horizontalLayout.addWidget(self.meta_input_fact)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.meta_label_manual = QtWidgets.QLabel(meta_widget)
        self.meta_label_manual.setMinimumSize(QtCore.QSize(0, 0))
        self.meta_label_manual.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.meta_label_manual.setBaseSize(QtCore.QSize(0, 0))
        self.meta_label_manual.setText("Edit:")
        self.meta_label_manual.setScaledContents(True)
        self.meta_label_manual.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_manual.setWordWrap(False)
        self.meta_label_manual.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.meta_label_manual.setObjectName("meta_label_manual")
        self.horizontalLayout_2.addWidget(self.meta_label_manual)
        self.meta_input_manual = QtWidgets.QLineEdit(meta_widget)
        self.meta_input_manual.setEnabled(True)
        self.meta_input_manual.setMinimumSize(QtCore.QSize(0, 0))
        self.meta_input_manual.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.meta_input_manual.setBaseSize(QtCore.QSize(0, 0))
        self.meta_input_manual.setAcceptDrops(False)
        self.meta_input_manual.setText("")
        self.meta_input_manual.setFrame(True)
        self.meta_input_manual.setObjectName("meta_input_manual")
        self.horizontalLayout_2.addWidget(self.meta_input_manual)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(meta_widget)
        QtCore.QMetaObject.connectSlotsByName(meta_widget)

    def retranslateUi(self, meta_widget):
        _translate = QtCore.QCoreApplication.translate
        meta_widget.setWindowTitle(_translate("meta_widget", "Form"))


