# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotWidget(object):
    def setupUi(self, PlotWidget):
        PlotWidget.setObjectName("PlotWidget")
        PlotWidget.resize(500, 107)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlotWidget.sizePolicy().hasHeightForWidth())
        PlotWidget.setSizePolicy(sizePolicy)
        PlotWidget.setMaximumSize(QtCore.QSize(16777215, 107))
        self.verticalLayout = QtWidgets.QVBoxLayout(PlotWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(PlotWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Data = QtWidgets.QWidget()
        self.Data.setObjectName("Data")
        self.gridLayout = QtWidgets.QGridLayout(self.Data)
        self.gridLayout.setContentsMargins(20, 0, -1, 0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        self.x_label = QtWidgets.QLabel(self.Data)
        self.x_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_label.setObjectName("x_label")
        self.gridLayout.addWidget(self.x_label, 0, 0, 1, 1)
        self.y_label = QtWidgets.QLabel(self.Data)
        self.y_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_label.setObjectName("y_label")
        self.gridLayout.addWidget(self.y_label, 1, 0, 1, 1)
        self.y_input = QtWidgets.QComboBox(self.Data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_input.sizePolicy().hasHeightForWidth())
        self.y_input.setSizePolicy(sizePolicy)
        self.y_input.setObjectName("y_input")
        self.gridLayout.addWidget(self.y_input, 1, 1, 1, 1)
        self.error_input = QtWidgets.QComboBox(self.Data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_input.sizePolicy().hasHeightForWidth())
        self.error_input.setSizePolicy(sizePolicy)
        self.error_input.setObjectName("error_input")
        self.gridLayout.addWidget(self.error_input, 2, 1, 1, 1)
        self.error_label = QtWidgets.QLabel(self.Data)
        self.error_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.error_label.setObjectName("error_label")
        self.gridLayout.addWidget(self.error_label, 2, 0, 1, 1)
        self.x_input = QtWidgets.QComboBox(self.Data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_input.sizePolicy().hasHeightForWidth())
        self.x_input.setSizePolicy(sizePolicy)
        self.x_input.setObjectName("x_input")
        self.gridLayout.addWidget(self.x_input, 0, 1, 1, 1)
        self.offset_label = QtWidgets.QLabel(self.Data)
        self.offset_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.offset_label.setObjectName("offset_label")
        self.gridLayout.addWidget(self.offset_label, 1, 2, 1, 1)
        self.offset_spin = QtWidgets.QDoubleSpinBox(self.Data)
        self.offset_spin.setMinimum(-100000000.0)
        self.offset_spin.setMaximum(100000000.0)
        self.offset_spin.setObjectName("offset_spin")
        self.gridLayout.addWidget(self.offset_spin, 1, 3, 1, 1)
        self.active_label = QtWidgets.QLabel(self.Data)
        self.active_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.active_label.setObjectName("active_label")
        self.gridLayout.addWidget(self.active_label, 0, 2, 1, 1)
        self.active_check = QtWidgets.QCheckBox(self.Data)
        self.active_check.setText("")
        self.active_check.setObjectName("active_check")
        self.gridLayout.addWidget(self.active_check, 0, 3, 1, 1)
        self.link_label = QtWidgets.QLabel(self.Data)
        self.link_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.link_label.setObjectName("link_label")
        self.gridLayout.addWidget(self.link_label, 2, 2, 1, 1)
        self.link_input = QtWidgets.QComboBox(self.Data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.link_input.sizePolicy().hasHeightForWidth())
        self.link_input.setSizePolicy(sizePolicy)
        self.link_input.setObjectName("link_input")
        self.gridLayout.addWidget(self.link_input, 2, 3, 1, 1)
        self.tabWidget.addTab(self.Data, "")
        self.Plot = QtWidgets.QWidget()
        self.Plot.setObjectName("Plot")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Plot)
        self.gridLayout_2.setContentsMargins(-1, 10, -1, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_type_label = QtWidgets.QLabel(self.Plot)
        self.line_type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.line_type_label.setObjectName("line_type_label")
        self.gridLayout_2.addWidget(self.line_type_label, 1, 1, 1, 1)
        self.scatter_size_spin = QtWidgets.QSpinBox(self.Plot)
        self.scatter_size_spin.setObjectName("scatter_size_spin")
        self.gridLayout_2.addWidget(self.scatter_size_spin, 0, 4, 1, 1)
        self.line_type_combo = QtWidgets.QComboBox(self.Plot)
        self.line_type_combo.setObjectName("line_type_combo")
        self.gridLayout_2.addWidget(self.line_type_combo, 1, 2, 1, 1)
        self.line_thickness_spin = QtWidgets.QSpinBox(self.Plot)
        self.line_thickness_spin.setObjectName("line_thickness_spin")
        self.gridLayout_2.addWidget(self.line_thickness_spin, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 5, 1, 1)
        self.line_check = QtWidgets.QCheckBox(self.Plot)
        self.line_check.setObjectName("line_check")
        self.gridLayout_2.addWidget(self.line_check, 1, 0, 1, 1)
        self.scatter_check = QtWidgets.QCheckBox(self.Plot)
        self.scatter_check.setObjectName("scatter_check")
        self.gridLayout_2.addWidget(self.scatter_check, 0, 0, 1, 1)
        self.scatter_size_label = QtWidgets.QLabel(self.Plot)
        self.scatter_size_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scatter_size_label.setObjectName("scatter_size_label")
        self.gridLayout_2.addWidget(self.scatter_size_label, 0, 3, 1, 1)
        self.scatter_type_label = QtWidgets.QLabel(self.Plot)
        self.scatter_type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.scatter_type_label.setObjectName("scatter_type_label")
        self.gridLayout_2.addWidget(self.scatter_type_label, 0, 1, 1, 1)
        self.line_thickness_label = QtWidgets.QLabel(self.Plot)
        self.line_thickness_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_thickness_label.setObjectName("line_thickness_label")
        self.gridLayout_2.addWidget(self.line_thickness_label, 1, 3, 1, 1)
        self.scatter_type_combo = QtWidgets.QComboBox(self.Plot)
        self.scatter_type_combo.setObjectName("scatter_type_combo")
        self.scatter_type_combo.addItem("")
        self.scatter_type_combo.addItem("")
        self.scatter_type_combo.addItem("")
        self.scatter_type_combo.addItem("")
        self.gridLayout_2.addWidget(self.scatter_type_combo, 0, 2, 1, 1)
        self.color_button = QtWidgets.QPushButton(self.Plot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color_button.sizePolicy().hasHeightForWidth())
        self.color_button.setSizePolicy(sizePolicy)
        self.color_button.setStyleSheet("#color_button{\n"
"background-color: rgb(106, 106, 106);\n"
"border-style: inset;\n"
"border-width: 2px}\n"
"\n"
"#color_button:pressed{\n"
"border-style: outset;\n"
"border-width: 2px}\n"
"")
        self.color_button.setText("")
        self.color_button.setAutoDefault(False)
        self.color_button.setFlat(False)
        self.color_button.setObjectName("color_button")
        self.gridLayout_2.addWidget(self.color_button, 2, 2, 1, 1)
        self.line_type_label_2 = QtWidgets.QLabel(self.Plot)
        self.line_type_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.line_type_label_2.setObjectName("line_type_label_2")
        self.gridLayout_2.addWidget(self.line_type_label_2, 2, 1, 1, 1)
        self.tabWidget.addTab(self.Plot, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(PlotWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PlotWidget)

    def retranslateUi(self, PlotWidget):
        _translate = QtCore.QCoreApplication.translate
        PlotWidget.setWindowTitle(_translate("PlotWidget", "Form"))
        self.x_label.setText(_translate("PlotWidget", "x input"))
        self.y_label.setText(_translate("PlotWidget", "y input"))
        self.error_label.setText(_translate("PlotWidget", "error"))
        self.offset_label.setText(_translate("PlotWidget", "offset"))
        self.active_label.setText(_translate("PlotWidget", "actif"))
        self.link_label.setText(_translate("PlotWidget", "link"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Data), _translate("PlotWidget", "Data"))
        self.line_type_label.setText(_translate("PlotWidget", "Type"))
        self.line_check.setText(_translate("PlotWidget", "Line Plot"))
        self.scatter_check.setText(_translate("PlotWidget", "Scatter Plot"))
        self.scatter_size_label.setText(_translate("PlotWidget", "Size"))
        self.scatter_type_label.setText(_translate("PlotWidget", "Type"))
        self.line_thickness_label.setText(_translate("PlotWidget", "Thickness"))
        self.scatter_type_combo.setItemText(0, _translate("PlotWidget", "circle"))
        self.scatter_type_combo.setItemText(1, _translate("PlotWidget", "square"))
        self.scatter_type_combo.setItemText(2, _translate("PlotWidget", "triangle"))
        self.scatter_type_combo.setItemText(3, _translate("PlotWidget", "diamond"))
        self.line_type_label_2.setText(_translate("PlotWidget", "Color"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Plot), _translate("PlotWidget", "Plot"))

